//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst_Approach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public string Course_id { get; set; }
        public string Course_title { get; set; }
        public string StartDate { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<int> Stud_id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
