//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_First_EFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Pid { get; set; }
        public string Ptitle { get; set; }
        public double Price { get; set; }
        public int Cid { get; set; }
    }
}
